### ISSUE TITLE
About neg

### ISSUE THREAD

**Issue by lebr0nli** [carlosrafaelgn/Asm86#13]
I compile and run this asm on my linux:
```asm
mov al, -128
neg al
```
Overflow flag will be `1` after `neg al`
But in this emulator, overflow flag is `0` after `neg al`
Is this a bug? I'm not very familiar with asm.

Thanks!

**Comment by carlosrafaelgn** [comment]
Hi, @lebr0nli !

Indeed, you are right! My bad!

I have just checked the official documentation [here](https://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-vol-2b-manual.html), on page 163, and `neg x` should behave as `x = 0 - x`, which sets the OV flag.

Fixed!!! 😅

Thanks for pointing it out! 🙏

Regards!
