### ISSUE TITLE
Question on syntax

### ISSUE THREAD

**Issue by DigiAngel** [carlosrafaelgn/Asm86#4]
The below snippet is from the book "Practical Reverse Engineering"
~~~
mov   dword ptr [eax], 1
mov   ecx, [eax]
mov   [eax], ebx
mov   [esi+0x34], eax
mov   eax, [esi+0x34]
mov   edx, [ecx+eax]
~~~

This fails to step through with:
~~~
Invalid writing address: 0x00000000
~~~

Is there a specific syntax I need to use?  Thank you.

**Comment by carlosrafaelgn** [comment]
Indeed an error will happen!
"mov   dword ptr [eax], 1" will throw a "Invalid writing address: 0x00000000" because eax contains 0 at the beginning of the execution.
You should set eax to a valid address before executing ;)
Regards!
