### ISSUE TITLE
ADD assumes 32-bit register size when setting flags

### ISSUE THREAD

**Issue by darkf** [carlosrafaelgn/Asm86#5]
e.g.:

    mov al,255
    add al,1

CF will not be set, when it should be. The code assumes that the register (AL) is 32-bit and checks flags accordingly.

**Comment by carlosrafaelgn** [comment]
Thanks for warning me!

I think this recent commit has fixed this issue. Can you confirm, so I can close this issue?

**Comment by darkf** [comment]
Yep, looks fixed. Thanks!

**Comment by carlosrafaelgn** [comment]
Thank you!! :+1:
