### ISSUE TITLE
Menus not closing, and windows not moveable

### ISSUE THREAD

**Issue by Benur21** [carlosrafaelgn/Asm86#6]
http://carlosrafaelgn.com.br/asm86/

Menus (eg: language) do not close when I click somewhere else, and when I try to move windows (eg: Console) it just selects everything.

**Comment by carlosrafaelgn** [comment]
Hi there!

The site itself is not part of the GitHub project. It is a live example of the classes in this project.

I must confess I have not given enough attention to the site in years...

Despite that, I have just tested here, and it works just fine (tested on desktop: IE 11, Edge, Firefox and Chrome, and tested on Chrome for Android).

Could you please tell me your OS and browser, so I could try to figure out what is going on?


Thanks.

**Comment by Benur21** [comment]
I don't know, but it's working now. Windows 10 Home 17134; Google Chrome v67.0.3396.99

It's working on these versions. Since April I must have updated both windows and google chrome. But I'm sure I was using Windows 10 and Google Chrome by the time I did this post.

**Comment by Benur21** [comment]
oops ^ (pressed "Close and comment" instead of "Comment")

**Comment by carlosrafaelgn** [comment]
👍 
No problems!!!
If everything works now, that is the important!

Thanks for letting me know!
