### ISSUE TITLE
SAR bug

### ISSUE THREAD

**Issue by mf85** [carlosrafaelgn/Asm86#8]
Hi, 
here's the issue.

"Using the SAR instruction to perform a division operation does not produce the same result as the IDIV instruction. The quotient from the IDIV instruction is rounded toward zero, whereas the “quotient” of the SAR instruction is rounded toward negative infinity. This difference is apparent only for negative numbers. For example, when the IDIV instruction is used to divide -9 by 4, the result is -2 with a remainder of -1. `If the SAR instruction is used to shift -9 right by two bits, the result is -3 and the “remainder” is +3; however, the SAR instruction stores only the most significant bit of the remainder (in the CF flag).`"
[https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf]

When I run this code
`mov al, -9`
`sar al, 2`
the result stored in `al` is 0x3D but it should be 0xFD(-3)
Tested on my local machine.

**Comment by carlosrafaelgn** [comment]
Thanks for pointing that out!
I have just fixed the issue!
I have not updated the JS file on the site, though. I will do it as soon as possible!
Again, thanks!
